### ISSUE TITLE
Multi-part messaging

### ISSUE THREAD

**Issue by asi96** [jaflaten/SikkerKommunikasjon#6]
Allocated time: **6 days** 4 in S2
A user should be able to send messages in multiple parts.

We need to implement a way to specify in the header that a message is multi-part before we send it.
The message will contain the SBD that we need to place inside.

- [ ] Specify header for message that it is multi-part
- [ ] Insert SBD into the message
- [ ] Send the message to integrasjonspunktet (error handling will have own issue)

**Comment by jaflaten** [comment]
Merged into development
